name: Docker Image CI

on:
  release:
    types: [ published ]

jobs:

  build-and-push-docker-image:
    
    name: Build Docker images and push to repositories
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2
      
    - name: Login to Docker Hub
      run: echo ${{secrets.DOCKERHUB_TOKEN}} | docker login -u ${{secrets.DOCKERHUB_USERNAME}} --password-stdin
      
    - name: Get the version
      id: vars
      run: echo ::set-output name=tag::$(echo ${GITHUB_REF:10})

    # Solr 8.4.1 HTTPS and Volumes support   
    - name: Build the 8.4.1 HTTPS and Volumes support Docker image
      run: docker compose -f SolrVersions/8.4.1/HttpsAndVolumesSupport/docker-compose.yml build --no-cache
      
    - name: Push the 8.4.1 latest Docker image
      run: docker push ivanbuzyka/solrcloud-8.4.1-httpsandvolumes:latest
    
    - name: Tag 8.4.1 Docker image
      run: docker tag ivanbuzyka/solrcloud-8.4.1-httpsandvolumes:latest ivanbuzyka/solrcloud-8.4.1-httpsandvolumes:${{steps.vars.outputs.tag}}
      
    - name: Push the 8.4.1 tagged Docker image
      run: docker push ivanbuzyka/solrcloud-8.4.1-httpsandvolumes:${{steps.vars.outputs.tag}}

    # Solr 8.4.1 HTTP and NO Volumes support
    - name: Build the 8.4.1 HTTP and NO Volumes support Docker image
      run: docker compose -f SolrVersions/8.4.1/HttpAndNoVolumes/docker-compose.yml build --no-cache
      
    - name: Push the 8.4.1 latest Docker image
      run: docker push ivanbuzyka/solrcloud-8.4.1-httpandnovolumes:latest
    
    - name: Tag 8.4.1 Docker image
      run: docker tag ivanbuzyka/solrcloud-8.4.1-httpandnovolumes:latest ivanbuzyka/solrcloud-8.4.1-httpandnovolumes:${{steps.vars.outputs.tag}}
      
    - name: Push the 8.4.1 tagged Docker image
      run: docker push ivanbuzyka/solrcloud-8.4.1-httpandnovolumes:${{steps.vars.outputs.tag}}

    # Solr 8.1.1 HTTPS and Volumes support   
    - name: Build the 8.1.1 HTTPS and Volumes support Docker image
      run: docker compose -f SolrVersions/8.1.1/HttpsAndVolumesSupport/docker-compose.yml build --no-cache
      
    - name: Push the 8.1.1 latest Docker image
      run: docker push ivanbuzyka/solrcloud-8.1.1-httpsandvolumes:latest
    
    - name: Tag 8.1.1 Docker image
      run: docker tag ivanbuzyka/solrcloud-8.1.1-httpsandvolumes:latest ivanbuzyka/solrcloud-8.1.1-httpsandvolumes:${{steps.vars.outputs.tag}}
      
    - name: Push the 8.1.1 tagged Docker image
      run: docker push ivanbuzyka/solrcloud-8.1.1-httpsandvolumes:${{steps.vars.outputs.tag}}
      # docker build . --file Dockerfile --tag my-image-name:$(date +%s)
    
    # Solr 8.1.1 HTTP and NO Volumes support   
    - name: Build the Solr 8.1.1 HTTP and NO Volumes support Docker image
      run: docker compose -f SolrVersions/8.1.1/HttpAndNoVolumes/docker-compose.yml build --no-cache
      
    - name: Push the 8.1.1 latest Docker image
      run: docker push ivanbuzyka/solrcloud-8.1.1-httpandnovolumes:latest
    
    - name: Tag 8.1.1 Docker image
      run: docker tag ivanbuzyka/solrcloud-8.1.1-httpandnovolumes:latest ivanbuzyka/solrcloud-8.1.1-httpandnovolumes:${{steps.vars.outputs.tag}}
      
    - name: Push the 8.1.1 tagged Docker image
      run: docker push ivanbuzyka/solrcloud-8.1.1-httpandnovolumes:${{steps.vars.outputs.tag}}
