name: Docker Image CI

on:
  release:
    types: [ published ]

jobs:

  build-and-push-docker-image:
    
    name: Build Docker images and push to repositories
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2
      
    - name: Login to Docker Hub
      run: echo ${{secrets.DOCKERHUB_TOKEN}} | docker login -u ${{secrets.DOCKERHUB_USERNAME}} --password-stdin
      
    - name: Get the version
      id: vars
      run: echo ::set-output name=tag::$(echo ${GITHUB_REF:10})

    # Solr 8.1.1   
    - name: Build the 8.1.1 Docker image
      run: docker compose -f 8.1.1/docker-compose.yml build
      
    - name: Push the 8.1.1 latest Docker image
      run: docker push ivanbuzyka/solrcloud-8.1.1:latest
    
    - name: Tag 8.1.1 Docker image
      run: docker tag ivanbuzyka/solrcloud-8.1.1:latest ivanbuzyka/solrcloud-8.1.1:${{steps.vars.outputs.tag}}
      
    - name: Push the 8.1.1 tagged Docker image
      run: docker push ivanbuzyka/solrcloud-8.1.1:${{steps.vars.outputs.tag}}
      # docker build . --file Dockerfile --tag my-image-name:$(date +%s)

    # Solr 8.4.1   
    - name: Build the 8.4.1 Docker image
      run: docker compose -f 8.4.1/docker-compose.yml build
      
    - name: Push the 8.4.1 latest Docker image
      run: docker push ivanbuzyka/solrcloud-8.4.1:latest
    
    - name: Tag 8.4.1 Docker image
      run: docker tag ivanbuzyka/solrcloud-8.4.1:latest ivanbuzyka/solrcloud-8.4.1:${{steps.vars.outputs.tag}}
      
    - name: Push the 8.4.1 tagged Docker image
      run: docker push ivanbuzyka/solrcloud-8.4.1:${{steps.vars.outputs.tag}}